packages:
  - packages/*
  - tools/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  "@lucide/vue": ^1.12.0
  "@types/node": ^25.6.0
  "@types/stats.js": ^0.17.4
  "@vitejs/plugin-vue": ^6.0.6
  "@vue-macros/define-render": ^3.1.2
  "@vue/compiler-dom": ^3.5.33
  "@vue/compiler-sfc": ^3.5.33
  bumpp: ^11.0.1
  overlayscrollbars: ^2.15.1
  playwright: ^1.59.1
  releaselog: ^7.0.2
  shiki: ^4.0.2
  simple-icons: ^16.18.0
  stats.js: ^0.17.0
  typescript: ^6.0.3
  unplugin-vue: ^7.2.0
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  vite-plus: 0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  void: 0.9.3
  vue: ^3.5.33
  vue-tsc: ^3.2.7
  vitest: 4.1.10
  "@vitest/browser-playwright": 4.1.10

catalogMode: prefer
minimumReleaseAgeExclude:
  - "@oxc-project/runtime@0.141.0"
  - "@oxc-project/types@0.141.0"
  - "@oxfmt/binding-android-arm-eabi@0.60.0"
  - "@oxfmt/binding-android-arm64@0.60.0"
  - "@oxfmt/binding-darwin-arm64@0.60.0"
  - "@oxfmt/binding-darwin-x64@0.60.0"
  - "@oxfmt/binding-freebsd-x64@0.60.0"
  - "@oxfmt/binding-linux-arm-gnueabihf@0.60.0"
  - "@oxfmt/binding-linux-arm-musleabihf@0.60.0"
  - "@oxfmt/binding-linux-arm64-gnu@0.60.0"
  - "@oxfmt/binding-linux-arm64-musl@0.60.0"
  - "@oxfmt/binding-linux-ppc64-gnu@0.60.0"
  - "@oxfmt/binding-linux-riscv64-gnu@0.60.0"
  - "@oxfmt/binding-linux-riscv64-musl@0.60.0"
  - "@oxfmt/binding-linux-s390x-gnu@0.60.0"
  - "@oxfmt/binding-linux-x64-gnu@0.60.0"
  - "@oxfmt/binding-linux-x64-musl@0.60.0"
  - "@oxfmt/binding-openharmony-arm64@0.60.0"
  - "@oxfmt/binding-win32-arm64-msvc@0.60.0"
  - "@oxfmt/binding-win32-ia32-msvc@0.60.0"
  - "@oxfmt/binding-win32-x64-msvc@0.60.0"
  - "@oxlint-tsgolint/darwin-arm64@7.0.2001"
  - "@oxlint-tsgolint/darwin-x64@7.0.2001"
  - "@oxlint-tsgolint/linux-arm64@7.0.2001"
  - "@oxlint-tsgolint/linux-x64@7.0.2001"
  - "@oxlint-tsgolint/win32-arm64@7.0.2001"
  - "@oxlint-tsgolint/win32-x64@7.0.2001"
  - "@oxlint/binding-android-arm-eabi@1.75.0"
  - "@oxlint/binding-android-arm64@1.75.0"
  - "@oxlint/binding-darwin-arm64@1.75.0"
  - "@oxlint/binding-darwin-x64@1.75.0"
  - "@oxlint/binding-freebsd-x64@1.75.0"
  - "@oxlint/binding-linux-arm-gnueabihf@1.75.0"
  - "@oxlint/binding-linux-arm-musleabihf@1.75.0"
  - "@oxlint/binding-linux-arm64-gnu@1.75.0"
  - "@oxlint/binding-linux-arm64-musl@1.75.0"
  - "@oxlint/binding-linux-ppc64-gnu@1.75.0"
  - "@oxlint/binding-linux-riscv64-gnu@1.75.0"
  - "@oxlint/binding-linux-riscv64-musl@1.75.0"
  - "@oxlint/binding-linux-s390x-gnu@1.75.0"
  - "@oxlint/binding-linux-x64-gnu@1.75.0"
  - "@oxlint/binding-linux-x64-musl@1.75.0"
  - "@oxlint/binding-openharmony-arm64@1.75.0"
  - "@oxlint/binding-win32-arm64-msvc@1.75.0"
  - "@oxlint/binding-win32-ia32-msvc@1.75.0"
  - "@oxlint/binding-win32-x64-msvc@1.75.0"
  - "@voidzero-dev/vite-plus-core@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89"
  - oxfmt@0.60.0
  - oxlint-tsgolint@7.0.2001
  - oxlint@1.75.0
  - vite-plus@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
