packages:
  - packages/*
  - tools/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  "@chenglou/pretext": 0.0.9
  "@lucide/vue": ^1.39.0
  "@types/node": ^26.4.1
  "@types/stats.js": ^0.17.4
  "@vitejs/plugin-vue": ^6.0.8
  "@vitest/browser-playwright": 5.0.1
  "@vue-macros/define-render": ^3.1.4
  "@vue/compiler-dom": ^3.5.42
  "@vue/compiler-sfc": ^3.5.42
  bumpp: ^12.2.3
  overlayscrollbars: ^2.15.1
  playwright: ^1.62.1
  releaselog: ^8.1.0
  shiki: ^4.4.3
  simple-icons: ^16.29.0
  stats.js: ^0.17.0
  typescript: npm:typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2
  unplugin-vue: ^7.2.0
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
  vite-plus: 0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
  void: 0.10.13
  vue: ^3.5.42
  vue-tsc: ^3.3.11
  vitest: 5.0.1

catalogMode: prefer

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67"
  - vite-plus@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67

overrides:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
